"""Run CodeQL queries generated by the LLM and collect findings."""

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Tuple

from config import _path_config
from llm import BaseLLMClient
from utils.codeql_native import CodeQLAnalyzer, load_codeql_config
from utils.git_utils import checkout_commit, get_git_commit
from utils.logger import get_logger

from .profile_query import generate_codeql_query_from_vuln_profile

logger = get_logger(__name__)


def save_verification_results(results: dict, output_file: Path) -> bool:
    try:
        with open(output_file, "w", encoding="utf-8") as handle:
            json.dump(results, handle, indent=2, ensure_ascii=False)
        logger.info(f"Results saved to: {output_file}")
        return True
    except Exception as exc:  # pylint: disable=broad-except
        logger.error(f"Failed to save verification results: {exc}")
        return False


def prepare_query_pack(query_dir: Path) -> Tuple[Path, Path]:
    query_dir.mkdir(parents=True, exist_ok=True)
    qlpack_file = query_dir / "qlpack.yml"
    qlpack_lock_file = query_dir / "codeql-pack.lock.yml"
    query_path = query_dir / "generated_query.ql"

    need_setup = not qlpack_lock_file.exists()
    if not need_setup:
        return query_path, qlpack_lock_file

    qlpack_content = """name: vuln-verify-queries
version: 1.0.0
dependencies:
  codeql/python-all: "*"
"""
    qlpack_file.write_text(qlpack_content, encoding="utf-8")

    logger.info("Installing CodeQL pack dependencies...")
    abs_query_dir = os.path.abspath(query_dir)
    install_result = subprocess.run(
        ["codeql", "pack", "install", abs_query_dir], capture_output=True, text=True
    )
    if install_result.returncode != 0:
        logger.error("Package install failed!")
        logger.error(f"STDERR: {install_result.stderr}")
        logger.info(f"STDOUT: {install_result.stdout}")
        raise RuntimeError("Failed to install CodeQL pack dependencies")

    if not qlpack_lock_file.exists():
        raise RuntimeError(f"Lock file not created at {qlpack_lock_file}")

    logger.info("Dependencies installed successfully")
    return query_path, qlpack_lock_file


def ensure_database(analyzer: CodeQLAnalyzer, repo_path: Path, db_name: str) -> Path:
    db_path = _path_config["codeql_db_path"] / db_name
    if db_path.exists():
        logger.info(f"Using existing database: {db_path}")
        return db_path

    logger.info(f"Creating CodeQL database at {db_path}...")
    success, db_result = analyzer.create_database(
        source_path=str(repo_path), language="python", database_name=db_name, overwrite=False
    )
    if not success:
        raise RuntimeError(f"Failed to create database: {db_result}")
    return Path(db_result)


def collect_findings(query_result: Dict[str, Any]) -> List[Dict[str, Any]]:
    runs = query_result.get("runs", []) if isinstance(query_result, dict) else []
    findings: List[Dict[str, Any]] = []
    for run in runs:
        findings.extend(run.get("results", []))
    return findings


def filter_findings_by_candidates(
    findings: List[Dict[str, Any]], candidates: List[Dict[str, Any]]
) -> None:
    for candidate in candidates:
        candidate["codeql_verification"] = {"codeql_found": False, "vulnerabilities": []}

    for idx, candidate in enumerate(candidates, 1):
        folder_paths = candidate.get("folder_paths", [])
        logger.info("=" * 80)
        logger.info(f"[{idx}/{len(candidates)}]")
        logger.info("=" * 80)
        if not folder_paths:
            logger.warning("No folder paths specified")
            continue

        for folder_path in folder_paths:
            logger.info(f"Checking folder: {folder_path}")
            relevant_findings: List[Dict[str, Any]] = []
            for finding in findings:
                locations = finding.get("locations", [])
                for loc in locations:
                    uri = (
                        loc.get("physicalLocation", {})
                        .get("artifactLocation", {})
                        .get("uri", "")
                    )
                    if folder_path in uri or uri.startswith(folder_path):
                        relevant_findings.append(finding)
                        break

            if not relevant_findings:
                logger.info(f"No vulnerabilities found in {folder_path}")
                continue

            logger.info(f"Found {len(relevant_findings)} vulnerabilities in {folder_path}")
            candidate["codeql_verification"]["codeql_found"] = True
            for finding in relevant_findings:
                rule_id = finding.get("ruleId", "custom-vuln-query")
                message = finding.get("message", {}).get("text", "No message")
                level = finding.get("level", "warning")
                locations = finding.get("locations", [])
                if locations:
                    loc = locations[0].get("physicalLocation", {})
                    uri = loc.get("artifactLocation", {}).get("uri", "")
                    region = loc.get("region", {})
                    start_line = region.get("startLine", "?")
                    candidate["codeql_verification"]["vulnerabilities"].append(
                        {
                            "rule_id": rule_id,
                            "message": message,
                            "level": level,
                            "file": uri,
                            "line": start_line,
                            "folder_path": folder_path,
                        }
                    )


def run_query_with_retry(
    analyzer: CodeQLAnalyzer,
    vulnerability_profile: dict,
    candidates: List[Dict[str, Any]],
    llm_client: BaseLLMClient,
    db_path: Path,
    query_path: Path,
    debug_query_path: Path,
    max_query_retries: int = 3,
) -> Tuple[bool, Dict[str, Any], str, int]:
    query_retry_count = 0
    query_success = False
    query_result: Dict[str, Any] = {}
    codeql_query = query_path.read_text(encoding="utf-8") if query_path.exists() else ""

    while not query_success and query_retry_count < max_query_retries:
        success, result = analyzer.run_query(
            database_path=str(db_path), query=str(query_path), output_format="sarif-latest"
        )

        if success:
            query_success = True
            query_result = result
            break

        error_msg = str(result)
        logger.error("Query execution failed")
        logger.error(error_msg)

        if any(
            keyword in error_msg.lower()
            for keyword in [
                "syntax error",
                "parse error",
                "compilation error",
                "invalid query",
                "expected",
                "could not resolve",
                "not found",
                "undefined",
            ]
        ):
            logger.warning("Detected CodeQL query error. Regenerating query...")
            query_retry_count += 1
            regenerate_success, new_query, regen_error = generate_codeql_query_from_vuln_profile(
                vulnerability_profile, llm_client, max_retries=5
            )
            if not regenerate_success:
                logger.error(f"Failed to regenerate query: {regen_error}")
                break
            codeql_query = new_query
            query_path.write_text(codeql_query, encoding="utf-8")
            debug_query_path.write_text(codeql_query, encoding="utf-8")
            logger.info("New query generated, retrying...")
        else:
            logger.error("Query execution failed with non-query error")
            break

    return query_success, query_result, codeql_query, query_retry_count


def run_codeql_scan(
    repo_name: str,
    vuln_commit: str,
    target_commit: str,
    cve_id: str,
    scan_llm: str,
    codeql_llm_provider: str,
    vulnerability_profile: dict,
    candidates: List[Dict[str, Any]],
    llm_client: BaseLLMClient,
) -> Dict[str, Any]:
    save_dir = Path(f"scan-results/{repo_name}_{vuln_commit}_{cve_id}/")
    output_dir = (
        Path(f"scan-results/{repo_name}_{target_commit}_{cve_id}_from_{vuln_commit[:12]}/")
        if vuln_commit != target_commit
        else save_dir
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    query_dir = output_dir / ".codeql" / "queries" / "vuln-verify"
    query_path, _ = prepare_query_pack(query_dir)
    debug_query_path = output_dir / "generated_codeql_query.ql"

    success, codeql_query, error = generate_codeql_query_from_vuln_profile(
        vulnerability_profile, llm_client, max_retries=10
    )
    if not success:
        raise RuntimeError(f"Failed to generate CodeQL query: {error}")

    query_path.write_text(codeql_query, encoding="utf-8")
    debug_query_path.write_text(codeql_query, encoding="utf-8")

    analyzer = CodeQLAnalyzer(config=load_codeql_config())
    if not analyzer.is_available:
        raise RuntimeError("CodeQL is not available. Please install CodeQL CLI.")

    repo_path = _path_config["repo_base_path"] / repo_name
    current_commit = get_git_commit(str(repo_path))
    if current_commit != target_commit:
        logger.info(f"Checking out {repo_name} to target commit {target_commit[:12]}...")
        if not checkout_commit(str(repo_path), target_commit):
            raise RuntimeError(f"Failed to checkout to {target_commit}")

    db_name = f"{repo_name}-{target_commit[:12]}"
    db_path = ensure_database(analyzer, repo_path, db_name)

    results_cache = db_path / "results"
    if results_cache.exists():
        shutil.rmtree(results_cache)

    query_success, query_result, codeql_query, query_retry_count = run_query_with_retry(
        analyzer,
        vulnerability_profile,
        candidates,
        llm_client,
        db_path,
        query_path,
        debug_query_path,
    )

    findings = collect_findings(query_result)
    filter_findings_by_candidates(findings, candidates)

    results: Dict[str, Any] = {
        "candidates": candidates,
        "vulnerability_profile": vulnerability_profile,
        "codeql_query": codeql_query,
        "total_findings": len(findings),
        "target_commit": target_commit,
        "vulnerability_commit": vuln_commit,
        "verification_summary": {
            "total_candidates": len(candidates),
            "codeql_found_vulnerable": sum(
                1 for cand in candidates if cand["codeql_verification"]["codeql_found"]
            ),
            "query_regenerations": query_retry_count,
            "tested_on_different_commit": vuln_commit != target_commit,
        },
    }

    output_file = output_dir / f"{codeql_llm_provider}_codeql_verification.json"
    save_verification_results(results, output_file)
    logger.info("Analysis complete")
    return results
